### ISSUE TITLE
Datos agroclimatologicos

### ISSUE THREAD

**Issue by juliofp** [SensingTools/atlas-ml#13]

**Comment by Muss13** [comment]
Servicio web que proporciona previsiones a 5 días de precipitación y evapotranspiración dadas unas coordenadas (latitud y longitud) en función de los datos obtenidos de la API de OpenWheather:

https://idearm.imida.es/cgi/etop/latitud/longitud

Ejemplo llamada: https://idearm.imida.es/cgi/etop/37.7629798/-0.9182167
